name: .Net Basics CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .NET/sample_code/MyConsoleApp/MyConsoleApp
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run Application
        run: dotnet run --no-build
      - name: Publish Application
        run: dotnet publish -c Release -o publish_output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: .NET/sample_code/MyConsoleApp/MyConsoleApp/publish_output